apiVersion: v1
kind: Pod
metadata:
  name: meupodazul
  labels:
    app: nginx
    versao: azul
spec:
  containers:
    - name: meucontainer
      image: kubedevio/nginx-color:blue
      imagePullPolicy: IfNotPresent
  restartPolicy: Always