apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.8
        volumeMounts:
          - mountPath: /data/db
            name: mongo-data
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        envFrom:
          - secretRef:
              name: mongodb-secret
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: scw-pvc