apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxaaa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxaaa
  template:
    metadata:
      labels:
        app: nginxaaa
    spec:
      containers:
        - name: nginxaaa
          image: nginx
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      affinity:
        podAffinity: #para afinidde
        #podAntiAffinity: para não afinidade
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - "nginxbbb"
              topologyKey: kubernetes.io/hostname #uma label que eu tenha no meu node