apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector: ## vai pegar todos os pods que possui app = a api
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
