apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  replicas: 2
  strategy:
    type: Recreate #mata todos os pods antes de subir (não e ideal)
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: kubedevio/api-versao:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: green-service
spec:
  type: NodePort
  selector:
    app: green
  ports:
  - port: 80
    targetPort: 80
