apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-color
  #namespace: blue
spec:
  selector:
    matchLabels:
      app: nginx-color
  template:
    metadata:
      labels:
        app: nginx-color
    spec:
      containers:
      - name: nginx-color
        image: kubedevio/nginx-color:blue
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
