apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deploy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deplyment # o que vou escalar
    name: api-deployment #nome do depoyment
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 10 # com base no request