apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-fabricio-net-cert
spec:
  secretName: fabricio-net-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-homolog
  dnsNames:
    - "api.traefik.com"