apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
      - name: api
        image: {{ .Values.api.image }}
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-api-configmap
        env:
        - name: Mongo__User
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_USERNAME
              {{- if empty .Values.mongodb.existSecret }}
              name: {{ .Release.Name }}-mongodb-secret
              {{- else }}
              name: {{ .Values.mongodb.existSecret }}-mongodb-secret
              {{- end }}
        - name: Mongo__Password
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_PASSWORD
              {{- if empty .Values.mongodb.existSecret }}
              name: {{ .Release.Name }}-mongodb-secret
              {{- else }}
              name: {{ .Values.mongodb.existSecret }}-mongodb-secret
              {{- end }}
        resources:
          requests:
            memory: "320Mi"
            cpu: "300m"
          limits:
            memory: "320Mi"
            cpu: "300m"