apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-mongodb
  ports:
  - port: 27017
    targetPort: 27017
