apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
      - name: api
        image: {{ .Values.api.image }}
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-api-configmap
          - secretRef:
              name: {{ .Release.Name }}-mongodb-secret
        resources:
          requests:
            memory: "320Mi"
            cpu: "300m"
          limits:
            memory: "320Mi"
            cpu: "300m"