apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
type: Opaque
data:
  #echo -n "mongouser" | base64
  Mongo__User: {{ .Values.mongodb.auth.username | b64enc | quote }}
  Mongo__Password: {{ .Values.mongodb.auth.password | b64enc | quote }}